version: '3.3' # docker-compose config version
volumes:
    mysql-data: {}
services:
    studentng:
        image: geokoshy89/student-ng:1.0.0
        depends_on:
             - studentapi
        ports:
            - "80:4200"
        restart: on-failure 
    studentapi: 
        image: geokoshy89/student-api:1.0.0 
        depends_on: 
            - database
        ports:
            - "8080:8080"
        restart: on-failure 
    database:
        image: geokoshy89/student-mysql 
        volumes: 
            - mysql-data:/var/lib/mysql 
        restart: on-failure  
        env_file:
            ./dev.env

